Fixes

diff --git a/showimage b/showimage
--- a/showimage
+++ b/showimage
@@ -1,6 +1,6 @@
 #!/bin/bash -eu
 
-die() { echo $* >&2; exit 1; }
+die() { echo "$*" >&2; exit 1; }
 
 usage() { die "\
 Usage:
@@ -20,7 +20,7 @@ Options are:
 display=""
 timeout=""
 
-while getopts ":d:t:" o do case $o in
+while getopts ":d:t:" o; do case $o in
     d) display=$OPTARG;;
     t) timeout="-t $OPTARG";;
     *) usage;;
@@ -30,20 +30,20 @@ shift $((OPTIND-1))
 (($# == 1)) || usage
 
 if type -p gm >/dev/null; then
-    convert = 'gm convert'
+    convert='gm convert'
 elif type -p convert >/dev/null; then
-    convert = 'convert'
+    convert='convert'
 else
     die "Requires package 'graphicsmagick' or 'imagemagick' to be installed"
 fi
 
 if ! [[ $display ]]; then
     display=$(tvservice -l | awk '/HDMI/{print $3; exit}' FS=' |,')
-    [[ $display ]] || die "Cn't find HDMI display"
+    [[ $display ]] || die "Can't find HDMI display"
 fi
 
-resolution = $(tvservice -sv$display | awk '{print $2}' FS=',' | awk '{print $1}')
+resolution=$(./dispmanx -r -d$display)
 [[ $resolution ]] || die "Can't get resolution for display $display"
 
 # convert the image to properly-sized RGB data and pipe to dispmanx
-$convert $1 -resize "!$resolution" -depth 8 "RGB:-" | ./dispmanx -d$display $timeout
+$convert $1 -resize !$resolution -depth 8 RGB:- | ./dispmanx -d$display $timeout
